/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.musteri;

import database.MasaCrud;
import form.BaslangicSinifi;
import form.giris.FrmMusteriGiris;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import property.Masa;
import property.Musteri;
import property.Siparis;

/**
 *
 * @author aylin
 */
public class FrmMusteriAnaSayfa extends javax.swing.JFrame {

    private Musteri musteri = null;
    private String masaId = "";
    static Siparis masaninSiparisi = new Siparis();
    Masa masa = null;

    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;

    public FrmMusteriAnaSayfa(String masaId) {
        initComponents();
        setLocationRelativeTo(this);
        if ((Masa) new MasaCrud().read(masaId).get(0) != null) {
            masa = (Masa) new MasaCrud().read(masaId).get(0);
            System.out.println("Masanın bilgileri:...... ");
            System.out.println(masa.getId());
            System.out.println(masa.getMasaAdi());
        }

        if (!masaId.equals("")) {
            System.out.println("eklenmek istenen masa id : " + masaId);
            int i = Integer.valueOf(masaId);
            masaninSiparisi.setMasaId(i);
        }
        lblMasaBilgileri.setText(masa.getMasaAdi());
        lblKullaniciBilgileri.setText("Misafir Oturumu");

        this.masaId = masaId;
        masaDurumDegistir(2);//Giris yapildiktan sonra masanı bos olarak gorunen durumu dolu yapildi.
    }

    public FrmMusteriAnaSayfa(Musteri musteri,
            String masaId) {
        initComponents();
        this.musteri = musteri;
        this.masaId = masaId;
        setLocationRelativeTo(this);
        if (musteri != null) {
            lblKullaniciBilgileri.setText(musteri.getIsim().toUpperCase() + " " + musteri.getSoyisim().toUpperCase());
        }

        Masa masa = (Masa) new MasaCrud().read(masaId).get(0);
        if (!masaId.equals("")) {
            int i = Integer.valueOf(masaId);
            masaninSiparisi.setMasaId(i);
        }
        lblMasaBilgileri.setText(masa.getMasaAdi());

        masaDurumDegistir(2);//Giris yapildiktan sonra masanı bos olarak gorunen durumu dolu yapildi.

    }

    void masaDurumDegistir(int durum) {
        Masa masa = new Masa();

        if (durum == 2) {

            if (musteri != null) {
                masa.setMusteriId(musteri.getId());
            }
        }

        masa.setId(Integer.valueOf(masaId));
        masa.setDurum(durum);
        new MasaCrud().update(masa);
    }

    FrmIstekSikayet ivs = new FrmIstekSikayet();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_GarsonCagir = new javax.swing.JButton();
        btn_Hesapİste = new javax.swing.JButton();
        btn_Kullaniciİslemleri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_İstekSikayet = new javax.swing.JButton();
        btn_Cikis = new javax.swing.JButton();
        btn_SiparisVer = new javax.swing.JButton();
        lblKullaniciBilgileri = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMasaBilgileri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("İşlemlerim");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Islemlerim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei UI", 1, 14), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 0, 0));

        btn_GarsonCagir.setBackground(new java.awt.Color(102, 102, 255));
        btn_GarsonCagir.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_GarsonCagir.setForeground(new java.awt.Color(102, 0, 0));
        btn_GarsonCagir.setText("Garson Cagir");
        btn_GarsonCagir.setPreferredSize(new java.awt.Dimension(150, 90));
        btn_GarsonCagir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GarsonCagirActionPerformed(evt);
            }
        });

        btn_Hesapİste.setBackground(new java.awt.Color(102, 102, 255));
        btn_Hesapİste.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_Hesapİste.setForeground(new java.awt.Color(102, 0, 0));
        btn_Hesapİste.setText("Hesap Iste");
        btn_Hesapİste.setPreferredSize(new java.awt.Dimension(150, 90));
        btn_Hesapİste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HesapİsteActionPerformed(evt);
            }
        });

        btn_Kullaniciİslemleri.setBackground(new java.awt.Color(102, 102, 255));
        btn_Kullaniciİslemleri.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_Kullaniciİslemleri.setForeground(new java.awt.Color(102, 0, 0));
        btn_Kullaniciİslemleri.setText("Kullanici Islemleri");
        btn_Kullaniciİslemleri.setPreferredSize(new java.awt.Dimension(150, 90));
        btn_Kullaniciİslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KullaniciİslemleriActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOŞGELDİNİZ");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 90));

        btn_İstekSikayet.setBackground(new java.awt.Color(102, 102, 255));
        btn_İstekSikayet.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_İstekSikayet.setForeground(new java.awt.Color(102, 0, 0));
        btn_İstekSikayet.setText("Istek-Sikayetler");
        btn_İstekSikayet.setPreferredSize(new java.awt.Dimension(150, 90));
        btn_İstekSikayet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_İstekSikayetActionPerformed(evt);
            }
        });

        btn_Cikis.setBackground(new java.awt.Color(102, 102, 255));
        btn_Cikis.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_Cikis.setForeground(new java.awt.Color(102, 0, 0));
        btn_Cikis.setText("ÇIKIS");
        btn_Cikis.setPreferredSize(new java.awt.Dimension(150, 90));
        btn_Cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CikisActionPerformed(evt);
            }
        });

        btn_SiparisVer.setBackground(new java.awt.Color(102, 102, 255));
        btn_SiparisVer.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_SiparisVer.setForeground(new java.awt.Color(102, 0, 0));
        btn_SiparisVer.setText("Siparis Ver");
        btn_SiparisVer.setPreferredSize(new java.awt.Dimension(150, 90));
        btn_SiparisVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SiparisVerActionPerformed(evt);
            }
        });

        lblKullaniciBilgileri.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        lblKullaniciBilgileri.setForeground(new java.awt.Color(102, 0, 0));
        lblKullaniciBilgileri.setText("Kullanıcı Adı Soyadı ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N

        lblMasaBilgileri.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        lblMasaBilgileri.setForeground(new java.awt.Color(102, 0, 0));
        lblMasaBilgileri.setText("Masa Bilgileri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_İstekSikayet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SiparisVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Kullaniciİslemleri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_GarsonCagir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Hesapİste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblKullaniciBilgileri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMasaBilgileri)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciBilgileri)
                    .addComponent(lblMasaBilgileri))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SiparisVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_GarsonCagir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Hesapİste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_İstekSikayet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kullaniciİslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CikisActionPerformed
        if (masaninSiparisi != null) {
            if (masaninSiparisi.getTutar().equals("")) {

                new FrmMusteriGiris(masaId).setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Lütfen çıkmadan önce hesabı kapatınız!!!");
            }
        }
    }//GEN-LAST:event_btn_CikisActionPerformed

    private void btn_SiparisVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SiparisVerActionPerformed
        System.out.println("gönderilen masaId : " + masaId);
        new FrmMusteriSiparis(musteri, masaId).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_SiparisVerActionPerformed

    private void btn_İstekSikayetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_İstekSikayetActionPerformed
        ivs.setVisible(true);

    }//GEN-LAST:event_btn_İstekSikayetActionPerformed

    private void btn_KullaniciİslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KullaniciİslemleriActionPerformed
        new FrmMusteriHesapAyarlari(musteri).setVisible(true);
    }//GEN-LAST:event_btn_KullaniciİslemleriActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        masaDurumDegistir(1);
        new FrmMusteriGiris(masaId).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_GarsonCagirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GarsonCagirActionPerformed
        String msgout = masaId + "," +  masa.getMasaAdi() + "," +  "Bakar mısınız?";
        try {
            BaslangicSinifi.dout.writeUTF(msgout);
        } catch (IOException ex) {
            Logger.getLogger(FrmMusteriAnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_GarsonCagirActionPerformed

    private void btn_HesapİsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HesapİsteActionPerformed
        try {

            String msgout = masaId + "," +  masa.getMasaAdi() + "," + "Hesabı alabilir miyiz?";
            BaslangicSinifi.dout.writeUTF(msgout);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_HesapİsteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMusteriAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMusteriAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMusteriAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMusteriAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMusteriAnaSayfa("").setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cikis;
    private javax.swing.JButton btn_GarsonCagir;
    private javax.swing.JButton btn_Hesapİste;
    private javax.swing.JButton btn_Kullaniciİslemleri;
    private javax.swing.JButton btn_SiparisVer;
    private javax.swing.JButton btn_İstekSikayet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKullaniciBilgileri;
    private javax.swing.JLabel lblMasaBilgileri;
    // End of variables declaration//GEN-END:variables
}
